// src/app/layout.tsx
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'aos/dist/aos.css';

import type { Metadata } from 'next';
import { EB_Garamond } from 'next/font/google';

import Header from '@/components/Header';
import Footer from '@/sections/Footer';

import './variables.css';
import './globals.css';

const ebGaramond = EB_Garamond({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Dog Chew',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ebGaramond.variable} ${ebGaramond.variable}`}>
        <Header />
        <main style={{ marginTop: '80px' }}> {/* Added margin-top */}
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
